# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 12:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nome bolletta')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Prezzo')),
                ('expiry_date', models.DateField(verbose_name='Data di scadenza')),
                ('payed', models.BooleanField(default=False, verbose_name='Pagata')),
                ('payed_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Data di pagamento')),
                ('payed_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Immagine bolletta pagata')),
            ],
            options={
                'verbose_name': 'Bolletta',
                'ordering': ('expiry_date',),
                'verbose_name_plural': 'Bollette',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nome spesa')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Prezzo')),
                ('payed_date', models.DateField(default=datetime.date.today, verbose_name='Data della spesa')),
                ('person', models.CharField(choices=[('L', 'Leo'), ('I', 'Isa')], max_length=1, verbose_name='Chi ha speso')),
            ],
            options={
                'verbose_name': 'Spesa',
                'ordering': ('payed_date',),
                'verbose_name_plural': 'Spese',
            },
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nome memo')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Prezzo')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Data della spesa')),
            ],
            options={
                'verbose_name': 'Memo',
                'ordering': ('expiry_date', 'title'),
                'verbose_name_plural': 'Memo',
            },
        ),
    ]
