# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deadlines', '0002_auto_20170505_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ('-payed_date',), 'verbose_name': 'Spesa', 'verbose_name_plural': 'Spese'},
        ),
        migrations.AlterField(
            model_name='bill',
            name='payed_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data di pagamento'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payed_image',
            field=models.ImageField(blank=True, null=True, upload_to='bill-images/%Y/%m/%d/', verbose_name='Immagine bolletta pagata'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='person',
            field=models.CharField(blank=True, choices=[('L', 'Leo'), ('I', 'Isa')], max_length=1, null=True, verbose_name='Chi ha pagato'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payed_date',
            field=models.DateField(verbose_name='Data della spesa'),
        ),
    ]
