# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadlines', '0003_auto_20170519_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='payed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data di pagamento'),
        ),
    ]
